### ISSUE TITLE
Some configured features aren't up to date in 1.20

### ISSUE THREAD

**Issue by Sniper1-1** [misode/misode.github.io#386]
I have noticed that the minecraft:huge_fungus configured feature is missing replaceable_blocks field seen in the [vanilla files](https://github.com/misode/mcmeta/blob/data-json/data/minecraft/worldgen/configured_feature/crimson_fungus.json). Additionally, the cherry trees are missing multiple fields present in their [vanilla file](https://github.com/misode/mcmeta/blob/data-json/data/minecraft/worldgen/configured_feature/cherry.json). I am unaware of other configured features that are missing parts, but I have not been able to check all of them. Currently, the output given by the generator for these features won't be accepted by Minecraft and will produce a datapack error.

**Comment by misode** [comment]
Fixed in 88d15173a0b3f9844abbb09fd3819577256535e5. Thank you for the report!

**Comment by Sniper1-1** [comment]
Thanks @misode, but there seems to still an issue for the cherry tree presets. It seems that it doesn't properly load the "branch_start_offset_from_top" field. It looks like it's the following:

`"branch_start_offset_from_top": {
        "max_inclusive": -3,
        "min_inclusive": -4
      }`

but it should be more like:

`"branch_start_offset_from_top": {
        "type": "minecraft:uniform",
        "value": {
          "min_inclusive": -4,
          "max_inclusive": -3
        }
      }`


(sorry if this should've been a new report)

**Comment by misode** [comment]
Oh thank you, I hadn't noticed that it was different! A fix is going out shortly
